{{- $redisPort := .Values.redis.master.service.ports.redis | toString -}}
{{- $redisHost := printf "tcp://%s-redis-master.%s.svc.cluster.local:%s" ( include "ultralims.fullname" . ) .Release.Namespace $redisPort -}}
{{- if .Values.redis.auth.password -}}
  {{- $redisHost = printf "%s?auth=%s" $redisHost .Values.redis.auth.password -}}
{{- end -}}
{{- $_redisHost := .Values.redis.enabled | ternary $redisHost .Values.config.redis.path -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ultralims.fullname" . }}
  labels:
    {{- include "ultralims.labels" . | nindent 4 }}
stringData:
  {{- with .Values.config }}
  DBDRIVE: {{ .db.driver }}
  db_server: {{ .db.name }}
  host_server: {{ .db.host }}
  password_server: {{ .db.password }}
  port_server: {{ .db.port | toString | quote }}
  user_server: {{ .db.user }}
  # Session on Redis
  SESSION_HANDLER: redis
  REDIS_PATH: {{ $_redisHost }}
  SESSION_PATH: {{ $_redisHost }}
  # JWT
  JWTWIZARD: {{ .jwt.wizard | quote }}
  JWTSECRET: {{ .jwt.secret | quote }}
  AZUREAPPSECRET: {{ .azureAppSecret | quote }}
  CLIENT_AREA_TOKEN_ID: {{ .oauth.tokenID }}
  CLIENT_AREA_TOKEN_SECRET: {{ .oauth.tokenSecret }}
  CLIENT_AREA_TOKEN_GRANT_TYPE: {{ .oauth.tokenGrantType }}
  CLIENT_AREA_TOKEN_SCOPE: {{ .oauth.tokenScope }}
  # novas variáveis
  IDCOMPANY: {{ .empresa_server | toString | quote }}
  DBNAME: {{ .db.name }}
  DBHOST: {{ .db.host }}
  DBUSER: {{ .db.user }}
  DBPASSWORD: {{ .db.password }}
  DBPORT: {{ .db.port | toString | quote }}
  {{- end }}
type: Opaque