apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ultralims.fullname" . }}
  labels:
    {{- include "ultralims.labels" . | nindent 4 }}
data:  
  {{- with .Values.config }}
  name_server: {{ .name_server }}
  empresa_server: {{ .empresa_server | toString | quote }}
  protocol_server: {{ .protocol_server }}
  URLIMPORTARESULTADO: {{ .importaResultado.url }}
  {{- end }}
  SESSION_HANDLER: redis
  APACHE_PORT: {{ .Values.service.port | toString | quote }}
  APACHE_LOG_DIR: "/tmp"
  APACHE_PID_FILE: "/tmp/apache2.pid"
  APACHE_RUN_GROUP: root
  APACHE_LOCK_DIR: "/tmp"
  APACHE_RUN_DIR: "/tmp"

