{{- if .Values.pvc.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ultralims.fullname" . }}-empresas
  labels:
    {{- include "ultralims.labels" . | nindent 4 }}
spec:
  {{- with .Values.pvc }}
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .storage.size }}
  storageClassName: {{ .storage.className }}
  volumeMode: Filesystem
  {{- end -}}
{{- end -}}
