kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "ultralims.fullname" . }}-empresas
  labels:
    {{- include "ultralims.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: thin-csi
  volumeMode: Filesystem
