kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ultralims.fullname" . }}
  labels:
    {{- include "ultralims.labels" . | nindent 4 }}
stringData:
  {{- with .Values.db }}
  DBDRIVE: {{ .driver }}
  db_server: {{ .name }}
  host_server: {{ .host }}
  password_server: {{ .password }}
  port_server: {{ .port | toString }}
  user_server: {{ .user }}
  {{- end }}
  {{- with .Values.redis }}
  REDIS_PATH: dGNwOi8vcmVkaXMtc2VydmVyOjYzNzk=
  {{- end }}
type: Opaque