kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ultralims.fullname" . }}
  labels:
    {{- include "ultralims.labels" . | nindent 4 }}
stringData:
  {{- with .Values.config }}
  DBDRIVE: {{ .db.driver }}
  db_server: {{ .db.name }}
  host_server: {{ .db.host }}
  password_server: {{ .db.password }}
  port_server: {{ .db.port | toString | quote }}
  user_server: {{ .db.user }}
  REDIS_PATH: {{ .redis.path }}
  JWTWIZARD: {{ .jwt.wizard }}
  JWTSECRET: {{ .jwt.secret }}
  AZUREAPPSECRET: {{ .azureAppSecret }}
  {{- end }}
type: Opaque