
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "ultralims.importaResultado.fullname" . }}
  labels:
    {{- include "ultralims.importaResultado.labels" . | nindent 4 }}
stringData:
  {{- with .Values.config.importaResultado }}
  DBDRIVE: {{ .db.driver }}
  DBNAME: {{ .db.name }}
  DBHOST: {{ .db.host }}
  DBPASSWORD: {{ .db.password }}
  DBPORT: {{ .db.port | toString | quote }}
  DBUSER: {{ .db.user }}
  {{- end }}
type: Opaque