apiVersion: v1
kind: Service
metadata:
  name: {{ include "ultralims.importaResultado.fullname" . }}
  labels:
    {{- include "ultralims.importaResultado.labels" . | nindent 4 }}
spec:
  type: {{ .Values.importaResultado.service.type }}
  ports:
    - port: {{ .Values.importaResultado.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ultralims.importaResultado.selectorLabels" . | nindent 4 }}
